"""empty message

Revision ID: 61367feac73f
Revises: 
Create Date: 2019-05-23 15:30:03.162638

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61367feac73f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student',
    sa.Column('admno', sa.Integer(), nullable=False),
    sa.Column('section', sa.String(length=80), nullable=True),
    sa.Column('Name', sa.String(length=80), nullable=True),
    sa.PrimaryKeyConstraint('admno')
    )
    op.create_table('teacher',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ecode', sa.String(length=80), nullable=True),
    sa.Column('Name', sa.String(length=80), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('teacher')
    op.drop_table('student')
    # ### end Alembic commands ###
