"""empty message

Revision ID: 67e9390bdb04
Revises: ff21b5efb224
Create Date: 2019-05-30 12:56:22.011599

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67e9390bdb04'
down_revision = 'ff21b5efb224'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('student_id_fkey', 'student', type_='foreignkey')
    op.drop_column('student', 'id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student', sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('student_id_fkey', 'student', 'teacher', ['id'], ['id'])
    # ### end Alembic commands ###
