"""empty message

Revision ID: d9f04187279c
Revises: 6785f3554a03
Create Date: 2019-05-30 11:23:31.710440

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd9f04187279c'
down_revision = '6785f3554a03'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('student_id_fkey', 'student', type_='foreignkey')
    op.drop_column('student', 'id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student', sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('student_id_fkey', 'student', 'teacher', ['id'], ['id'])
    # ### end Alembic commands ###
