"""empty message

Revision ID: e104650584e8
Revises: 
Create Date: 2019-08-19 21:05:13.517489

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e104650584e8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student',
    sa.Column('admno', sa.Integer(), nullable=False),
    sa.Column('section', sa.String(length=80), nullable=True),
    sa.Column('Name', sa.String(length=80), nullable=True),
    sa.Column('password', sa.String(length=80), nullable=True),
    sa.PrimaryKeyConstraint('admno')
    )
    op.create_table('teacher',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=True),
    sa.Column('password', sa.String(length=80), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('marks',
    sa.Column('no', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('admno', sa.Integer(), nullable=True),
    sa.Column('marks', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['admno'], ['student.admno'], ),
    sa.ForeignKeyConstraint(['id'], ['teacher.id'], ),
    sa.PrimaryKeyConstraint('no')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('marks')
    op.drop_table('teacher')
    op.drop_table('student')
    # ### end Alembic commands ###
