"""empty message

Revision ID: 9c56b3c652e4
Revises: fdcfc34b6f94
Create Date: 2019-06-07 16:55:45.079946

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c56b3c652e4'
down_revision = 'fdcfc34b6f94'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student', sa.Column('teacher_id', sa.Integer(), nullable=True))
    op.drop_constraint('student_id_fkey', 'student', type_='foreignkey')
    op.create_foreign_key(None, 'student', 'teacher', ['teacher_id'], ['id'])
    op.drop_column('student', 'id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student', sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'student', type_='foreignkey')
    op.create_foreign_key('student_id_fkey', 'student', 'teacher', ['id'], ['id'])
    op.drop_column('student', 'teacher_id')
    # ### end Alembic commands ###
